### ISSUE TITLE
Why OpenSolver?

### ISSUE THREAD

**Issue by GCuser99** [Mouad4399/-Asymmetric-Symmetric-TSP-Solver-in-excel#1]
Hi - nice project. I was searching GitHub for Solver problems to test a code library of mine and came across your project. Was wondering why you are using OpenSolver - it seems the Solver Add-in that comes with Excel solves the problem for 5 or 6 cities just fine.  Your code in the Excel file uses Solver to solve the problem, and then follows that with a call to OpenSolver. Is there a compelling reason for that? Thx!

EDIT: actually Solver can handle up to the 9-city case. I see that the .bas code module you provided is different than the one contained in the Excel file. In the code module, you commented out the unnecessary call to Solver (it was not commented out in the Excel file). So I'm sure you're using OpenSolver to be able to solve cases > 9 cities. I'll close this one.

**Comment by Mouad4399** [comment]
yep, you are right, also OpenSolver comes with different engines. 

Impressive though! You hit the nail on the head. Well Done.
